# Generated by Django 5.0.4 on 2024-05-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='images',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=3000, upload_to='service_images/'),
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
