# Generated by Django 5.0.4 on 2024-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='backgroundApp',
            field=models.ImageField(blank=True, null=True, upload_to='Back_logo/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='Back_logo/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=3000, upload_to='carousel_images/'),
        ),
    ]
