# Generated by Django 5.2.4 on 2025-07-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
    ]
